logging:
  level:
    org.springframework.security.oauth2: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${myapp.oauth2.issuer-uri}
      client:
        registration:
          msvc-users-client:
            provider: ${myapp.oauth2.provider}
            client-id: ${myapp.oauth2.client-id}
            client-secret: ${myapp.oauth2.client-secret}
            authorization-grant-type: ${myapp.oauth2.authorization-grant-type}
            redirect-uri: ${myapp.oauth2.redirect-uri}
            scope: ${myapp.oauth2.scope}
            client-name: ${myapp.oauth2.client-name}
        provider:
          spring:
            issuer-uri: ${myapp.oauth2.issuer-uri}
